# Generated by Django 5.1 on 2024-12-30 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCAPP', '0002_categories_status_visibility_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mindmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.TextField()),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasearchs_mindmap', to='RCAPP.project')),
            ],
        ),
    ]
