# Generated by Django 5.1 on 2025-01-01 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCAPP', '0003_mindmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.TextField()),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasearchs_chart', to='RCAPP.project')),
            ],
        ),
    ]
