# Generated by Django 5.1 on 2025-01-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RCAPP', '0004_charts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charts',
            new_name='Chart',
        ),
    ]
